name: typofixer-da
parent: default
matches:
- triggers: ["abbonnement","abbonement","abonement"]
  replace: "abonnement"
  word: true
  propagate_case: true
- triggers: ["accellerere","acelerere"]
  replace: "accelerere"
  word: true
  propagate_case: true
- trigger: "addresse"
  replace: "adresse"
  word: true
  propagate_case: true
- trigger: "afhængelig"
  replace: "afhængig"
  word: true
  propagate_case: true
- trigger: "afspassere"
  replace: "afspadsere"
  word: true
  propagate_case: true
- triggers: ["arangement","arrengement","arengement"]
  replace: "arrangement"
  word: true
  propagate_case: true
- trigger: "af vide"
  replace: "at vide"
  word: true
  propagate_case: true
- trigger: "barbeque"
  replace: "barbecue"
  word: true
  propagate_case: true
- trigger: "bekræftigelse"
  replace: "bekræftelse"
  word: true
  propagate_case: true
- triggers: ["bordou","bordeux","bordaux"]
  replace: "bordeaux"
  word: true
  propagate_case: true
- triggers: ["bulion","boulion","boullion"]
  replace: "bouillon"
  word: true
  propagate_case: true
- trigger: "brochurre"
  replace: "brochure"
  word: true
  propagate_case: true
- triggers: ["buget","byget","bydget"]
  replace: "Budget"
  word: true
  propagate_case: true
- triggers: ["byro","buro","burau"]
  replace: "bureau"
  word: true
  propagate_case: true
- triggers: ["chafør","chaffør","chuaffør"]
  replace: "chauffør"
  word: true
  propagate_case: true
- trigger: "dte"
  replace: "det"
  word: true
  propagate_case: true
- trigger: "diamentral"
  replace: "diametral"
  word: true
  propagate_case: true
- trigger: "diciplin"
  replace: "disciplin"
  word: true
  propagate_case: true
- triggers: ["diskusion","diskution"]
  replace: "diskussion"
  word: true
  propagate_case: true
- trigger: "dyrelæge"
  replace: "dyrlæge"
  word: true
  propagate_case: true
- trigger: "excl."
  replace: "ekskl."
  word: true
  propagate_case: true
- triggers: ["i nu","inu"]
  replace: "endnu"
  word: true
  propagate_case: true
- trigger: "financiere"
  replace: "finansiere"
  word: true
  propagate_case: true
- trigger: "forspørgsel"
  replace: "forespørgsel"
  word: true
  propagate_case: true
- trigger: "forsæt"
  replace: "fortsæt"
  word: true
  propagate_case: true
- trigger: "fælleskab"
  replace: "fællesskab"
  word: true
  propagate_case: true
- trigger: "hra"
  replace: "har"
  word: true
  propagate_case: true
- trigger: "holdte"
  replace: "holdt"
  word: true
  propagate_case: true
- trigger: "hovede"
  replace: "hoved"
  word: true
  propagate_case: true
- triggers: ["hygiegne","hygiajne"]
  replace: "hygiejne"
  word: true
  propagate_case: true
- trigger: "ialt"
  replace: "i alt"
  word: true
  propagate_case: true
- trigger: "idag"
  replace: "i dag"
  word: true
  propagate_case: true
- trigger: "ihvertfald"
  replace: "i hvert fald"
  word: true
  propagate_case: true
- trigger: "imorgen"
  replace: "I morgen"
  word: true
  propagate_case: true
- triggers: ["ingenør","inginør","ingeinør"]
  replace: "ingeniør"
  word: true
  propagate_case: true
- triggers: ["intiativ","initiv"]
  replace: "initiativ"
  word: true
  propagate_case: true
- trigger: "incl"
  replace: "inkl."
  word: true
  propagate_case: true
- triggers: ["intrasant","interesant","intresant","intressant"]
  replace: "interessant"
  word: true
  propagate_case: true
- triggers: ["interveiw","interwiev","interweiv"]
  replace: "interview"
  word: true
  propagate_case: true
- triggers: ["jfr.","jvf."]
  replace: "jf."
  word: true
  propagate_case: true
- triggers: ["kaptagn","kaptegn","kaptain"]
  replace: "kaptajn"
  word: true
  propagate_case: true
- triggers: ["karusel","karussel","karrussel"]
  replace: "karrusel"
  word: true
  propagate_case: true
- triggers: ["konklution","konklussion"]
  replace: "konklusion"
  word: true
  propagate_case: true
- trigger: "linie"
  replace: "linje"
  word: true
  propagate_case: true
- trigger: "massere"
  replace: "masser"
  word: true
  propagate_case: true
- trigger: "med mindre"
  replace: "medmindre"
  word: true
  propagate_case: true
- triggers: ["nivou","nivau","nevou","nivaue"]
  replace: "niveau"
  word: true
  propagate_case: true
- triggers: ["palietter","pallietter","pailetter"]
  replace: "pailletter"
  word: true
  propagate_case: true
- triggers: ["parralel","parrallel","paralel"]
  replace: "parallel"
  word: true
  propagate_case: true
- trigger: "parantes"
  replace: "parentes"
  word: true
  propagate_case: true
- triggers: ["priotering","pritering"]
  replace: "prioritering"
  word: true
  propagate_case: true
- triggers: ["proffessionel","profesionel","professionel"]
  replace: "professionel"
  word: true
  propagate_case: true
- trigger: "poc"
  replace: "Proof of Concept"
  word: true
  propagate_case: true
- trigger: "provensiel"
  replace: "provinsiel"
  word: true
  propagate_case: true
- trigger: "åp"
  replace: "på"
  word: true
  propagate_case: true
- trigger: "raport"
  replace: "rapport"
  word: true
  propagate_case: true
- trigger: "reflektion"
  replace: "refleksion"
  word: true
  propagate_case: true
- triggers: ["resource","resurce","ressourse"]
  replace: "ressource"
  word: true
  propagate_case: true
- triggers: ["resuarant","resourant","restaurent"]
  replace: "restaurant"
  word: true
  propagate_case: true
- triggers: ["rutchebane","rutshebane","rutschebane"]
  replace: "rutsjebane"
  word: true
  propagate_case: true
- triggers: ["sattelitter","sattellitter"]
  replace: "satellitter"
  word: true
  propagate_case: true
- triggers: ["sekrætær","sekratær"]
  replace: "sekretær"
  word: true
  propagate_case: true
- trigger: "selvskab"
  replace: "selskab"
  word: true
  propagate_case: true
- trigger: "seperat"
  replace: "separat"
  word: true
  propagate_case: true
- trigger: "sku"
  replace: "sgu"
  word: true
  propagate_case: true
- trigger: "sindsygt"
  replace: "sindssygt"
  word: true
  propagate_case: true
- triggers: ["snaksaglig","snaksalig"]
  replace: "snakkesalig"
  word: true
  propagate_case: true
- triggers: ["suvenir","souvinir"]
  replace: "souvenir"
  word: true
  propagate_case: true
- trigger: "standart"
  replace: "standard"
  word: true
  propagate_case: true
- trigger: "staniol"
  replace: "stanniol"
  word: true
  propagate_case: true
- trigger: "størrere"
  replace: "større"
  word: true
  propagate_case: true
- triggers: ["suces","success"]
  replace: "succes"
  word: true
  propagate_case: true
- trigger: "tastetur"
  replace: "tastatur"
  word: true
  propagate_case: true
- trigger: "teknsiske"
  replace: "tekniske"
  word: true
  propagate_case: true
- triggers: ["terasse","terresse","teresse"]
  replace: "terrasse"
  word: true
  propagate_case: true
- trigger: "udemærket"
  replace: "udmærket"
  word: true
  propagate_case: true
- trigger: "ynglingsfilm"
  replace: "yndlingsfilm"
  word: true
  propagate_case: true
- triggers: ["yugurt","yughurt","yougurt","youghurt","yogurt"]
  replace: "yoghurt"
  word: true
  propagate_case: true
- trigger: "ærgelig"
  replace: "ærgerlig"
  word: true
  propagate_case: true
