name: name fixer
parent: default
matches:
  - trigger: "travis"
    replace: Travis
    word: true
  - trigger: "timmy"
    replace: Timmy
    word: true
  - trigger: "jackson"
    replace: Jackson
    word: true
  - trigger: "alex"
    replace: Alex
    word: true
  - trigger: "artur"
    replace: Artur
    word: true
  - trigger: "davis"
    replace: Davis
    word: true
  - trigger: "oliviér"
    replace: Oliviér
    word: true
  - trigger: "olivier"
    replace: Olivier
    word: true
  - trigger: "illyan"
    replace: Illyan
    word: true
  - trigger: "toni"
    replace: Toni
    word: true
  ## Graduates
  - trigger: "eleni"
    replace: Eleni
    word: true
  - trigger: "ray"
    replace: Ray
    word: true
  - trigger: lisa
    replace: Lisa
    word: true
  - trigger: "laura"
    replace: Laura
    word: true
  - trigger: "shan"
    replace: Shan
    word: true
  - trigger: "jeffrey"
    replace: Jeffrey
    word: true
  - trigger: "maria"
    replace: Maria
    word: true
  - trigger: "mathias"
    replace: Mathias
    word: true
  - trigger: "luyao"
    replace: Luyao
    word: true
  - trigger: "anne sophie"
    replace: "Anne Sophie"
    word: true
  - trigger: "johan"
    replace: Johan
    word: true
  ## Digital Innovation
  - trigger: "thomas"
    replace: Thomas
    word: true
  - trigger: "bex"
    replace: Bex
    word: true
  - trigger: "bergdis"
    replace: Bergdis
    word: true
  - trigger: "morten"
    replace: Morten
    word: true
  - trigger: "xiang"
    replace: Xiang
    word: true
  - trigger: "spyridon"
    replace: Spyridon
    word: true
  ## Digital Platforms
  - trigger: "troels"
    replace: Troels
    word: true
  - trigger: "lasse"
    replace: Lasse
    word: true
  - trigger: "himanshu"
    replace: Himanshu
    word: true
  - trigger: "cornelia"
    replace: Cornelia
    word: true
  - trigger: "salik"
    replace: Salik
    word: true
  ## Valuable people
  - trigger: "stefan"
    replace: Stefan
    word: true
  - trigger: "kenneth"
    replace: Kenneth
    word: true
  ## Places
  - trigger: "chicago"
    replace: Chicago
    word: true
  - trigger: "chiago"
    replace: Chicago
    word: true
  - trigger: "ballerup"
    replace: Ballerup
    word: true
  - trigger: "balerup"
    replace: Ballerup
    word: true

  - trigger: "mountain view"
    replace: "Mountain View"

  - trigger: "san francisco"
    replace: "San Francisco"

  - trigger: "new york"
    replace: "New York"

  ## Companies

  - trigger: "resound"
    replace: "ReSound"
    propagate_case: true
    word: true

  - triggers: ["jabra"]
    replace: "Jabra"
    propagate_case: true
    word: true

  - triggers: ["steelseries", "steelseeries", "stelseries"]
    replace: "SteelSeries"
    propagate_case: true
    word: true

  - trigger: "microsoft"
    replace: Microsoft
    word: true

  - trigger: "windows"
    replace: Windows
    word: true
  - trigger: "denmark"
    replace: Denmark
    word: true

  - trigger: "digital platform architecture"
    replace: "Digital Platform Architecture"
