name: name fixer
parent: default
matches:
  - regex: travis
    replace: Travis
    word: true
  - regex: timmy
    replace: Timmy
    word: true
  - regex: jackson
    replace: Jackson
    word: true
  - regex: alex
    replace: Alex
    word: true
  - regex: artur
    replace: Artur
    word: true
  - regex: davis
    replace: Davis
    word: true
  - regex: oliviér
    replace: Oliviér
    word: true
  - regex: olivier
    replace: Oliviér
    word: true
  - regex: illyan
    replace: Illyan
    word: true
  - regex: toni
    replace: Toni
    word: true
